sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - 6.0
  - 5.0
  - 4.0
  - 0.12
before_install:
  - npm i -g npm@^2.0.0
  - npm i -g babel
  - npm i -g browserify
before_script:
  - npm prune
script:
  - npm run test:single
  - npm run check-coverage
after_success:
  - npm run semantic-release
